import { defineMctoolsConfig } from '@mctools/eslint-plugin-zs/config'

// Single source of truth lives in `@mctools/eslint-plugin-zs/config`, shared
// with the Enigmatica2Expert-Extended modpack repo — one config, one style.
export default await defineMctoolsConfig({
  tsconfigPath: 'tsconfig.json',
  ignores     : [
    '**/dist/**',
    '**/test/fixtures/**',
    // Generated by `pnpm build:readme` (scripts/build/readme.ts).
    '**/README.md',
    'packages/format/src/parser-generated.mjs',
    'packages/*/scripts/**',
  ],
})
