#!/usr/bin/env tsx

import type { Minecraftinstance } from '@mctools/curseforge/minecraftinstance'
import { readFileSync, writeFileSync } from 'node:fs'
import process from 'node:process'
import { assertPath } from '@mctools/utils/args'
import chalk from 'chalk'
import { defineCommand, runMain } from 'citty'

import { generateModsList } from './index.js'

const main = defineCommand({
  meta: {
    name       : '@mctools/modlist',
    description: 'Generate .md file with all mods listed',
  },
  args: {
    key: {
      type       : 'string',
      alias      : 'k',
      description: 'CurseForge API key or path to file containing it. Get one at https://console.curseforge.com/?#/api-keys. If omitted, CF_API_KEY env var is used.',
    },
    ignore: {
      type       : 'string',
      alias      : 'i',
      description: 'Path to .gitignore-like file to exclude dev-only mods.',
    },
    mcinstance: {
      type       : 'string',
      alias      : 'm',
      default    : 'minecraftinstance.json',
      description: 'Path to minecraftinstance.json (generated by CurseForge launcher).',
    },
    old: {
      type       : 'string',
      alias      : 'l',
      description: 'Path to old instance json to compare with (for changelog generation).',
    },
    changelog: {
      type       : 'boolean',
      default    : true,
      description: 'Fetch changelogs for updated mods from CurseForge API. Use --no-changelog to disable.',
    },
    template: {
      type       : 'string',
      alias      : 't',
      description: 'Path to Handlebar template.',
    },
    sort: {
      type       : 'string',
      alias      : 's',
      default    : 'addonID',
      description: 'Sort field of CurseForge addon (e.g. cf2Addon.downloadCount). Prefix with / to reverse order.',
    },
    output: {
      type       : 'string',
      alias      : 'o',
      default    : 'MODS.md',
      description: 'Path to output file.',
    },
    verbose: {
      type       : 'boolean',
      alias      : 'v',
      description: 'Log working process in stdout.',
    },
  },
  async run({ args }) {
    let key = args.key
    if (key) {
      try {
        key = readFileSync(assertPath(key), 'utf8').trim()
      }
      catch { key = args.key }
    }
    key ??= process.env.CF_API_KEY as string

    if (!key) {
      console.error(chalk.red`Provide Curse Forge API key with ` + chalk.yellow`--key` + chalk.red` cli option or with ` + chalk.yellow`CF_API_KEY` + chalk.red` environment variable`)
      process.exit(1)
    }

    const ignore = args.ignore ? readFileSync(assertPath(args.ignore), 'utf8') : undefined
    const mcinstance = JSON.parse(readFileSync(assertPath(args.mcinstance), 'utf8')) as Minecraftinstance
    const old = args.old ? JSON.parse(readFileSync(assertPath(args.old), 'utf8')) as Minecraftinstance : undefined
    const template = args.template ? readFileSync(assertPath(args.template), 'utf8') : undefined

    if (args.verbose) console.log('- Generating Modlist -')
    const content = await generateModsList({
      fresh    : mcinstance,
      old,
      key,
      ignore,
      sort     : args.sort,
      template,
      changelog: args.changelog,
      verbose  : args.verbose,
      onLog    : msg => process.stdout.write(msg),
    }).catch((e: unknown) => {
      console.error(e)
      process.exit(1)
    })
    writeFileSync(args.output, content)
  },
})

void runMain(main)
