###############################
# Configuration for @mct/errors
###############################

# If you want to make modpack-related config, copy and modify this one
# and feed it to @mct/errors with argument

# All strings except replace.to is JS RegExes

###############################

# We can cut only partial of log if we dont want to list all the errors
boundries: 
  from:
  to: '[Server thread/' # Server thread started when player joining world

# RegEx to match log.
# Default confir matches all Warnings and Errors in debug.log
#       ╔═══════════════════ Regular errors ════════════════════╗╔════════════════════════════════════════ ASM errors that takes several lines ══════════════════════════════════════════════════════════════════╗
match: '^\[\d+:\d+:\d+\] \[[^\]]+(WARN|ERROR)\]([\s\S\n](?!^\[))+(\n\[\d+:\d+:\d+\] \[Client thread/ERROR\] \[FML\]: Index: \d+ Listeners:\r?\n(\[\d+:\d+:\d+\] \[Client thread/ERROR\] \[FML\]: \d+: .+\r?\n?)+)?'

# Before output errors, all this replaces would be applied to resulted element
replace:
  # Remove timestamps
  - from: '^\[\d+:\d+:\d+\] '
    to: ''

  # Remove hash codes
  - from: '@[0-9a-f]{4,8}'
    to: '@xxxxxxxx'

  # Cut long stack traces
  - from: '(?<cap>(^[^\n]*$\n){5})([^\n]*\n.*)+'
    to: $<cap>  [...]

# RegExps to remove entries from output
ignore:
  # FML errors that most mods have, no harm
  - '\[FML\]: The coremod .+ is not signed!'
  - '\[FML\]: The coremod .+ does not have a MCVersion annotation'
  - '\[FML\]: Found .+ should be in a separate jar from the coremod.'
  - '\[FML\]: Potentially Dangerous alternative prefix `.+`'
  - "\\[FML\\]: Mod .+ is missing the required element 'version'"
  - '\[LaunchWrapper\]: Tweak class name .+ has already been visited'

  # Warning about Forge Debug
  - ': ==( Forge Debug Logging is ENABLED|=+)?'

  # FML mod signature errors
  - '\[FML\]: The mod .* is expecting signature.*however there is no signature matching that description'
  - '\[FML\]: FML appears to be missing any signature data. This is not a good thing'

  # Most likely happens when recipe changed and recipe name was changed too
  - '\[net.minecraft.advancements.AdvancementList\]: Couldn.t load advancement'

  # Errors of loading models, have no effects in game
  - 'ERROR. \[FML\]: Exception loading (model|blockstate) for( the)? variant'
  - 'ERROR. \[FML\]: MultiModel minecraft:builtin/missing is empty'
  - 'ERROR. \[FML\]: Could not load override model'
  - 'WARN. \[FML\]: OBJModel.Parser: found a face .+ with more than 4 vertices'

  # Ignore missing textures (actually, they are unused)
  - '\[net.minecraft.client.renderer.texture.TextureMap\]: Using missing texture. unable to load '

  # Parsing recipe errors from FML. Probably items just removed but recipe reference is present
  - '\[FML\]: Parsing error loading recipe '

  # Warnings that not changing game, just notes
  - '\[CoFH World\]: Using `metadata` .+ for blocks is deprecated'

  # Guide-API error - mod for JSON books documentation for mods. Unrelated to CraftTweaker
  - '\[Guide-API\]: Cannot get renderer for recipe type class crafttweaker.mc1120.recipes.MCRecipeShaped'

  # Ignore Compact machines disabled recipes
  - '\[compactmachines3\]: Could not deserialize recipe from file:'

  # Warnings that actually a jokes
  - '\[enderio\]: TConstruct. you fail again. muhaha! The world is mine. mine!'
  - '\[enderio\]: Applied Energistics conduits loaded. Let your networks connect!'
  - '\[enderio\]: OpenComputers conduits loaded. Let your networks connect!'
  - '\[enderio\]: Forestry integration loaded. Let things grow.'
  - '\[enderio\]: Mekanism Gas conduits loaded. Let your networks connect!'

  # Warnings about absent mods
  - '\[enderio\]: Refined Storage conduits NOT loaded. Refined Storage is not installed'
  - '\[enderio\]: Could not find Build Craft Wrench definition. Wrench integration with other mods may fail'

  # Doesnt change anything in game
  - 'ERROR. \[(tconstruct-(API|modifier)|conarm)\]: (Could not|Cannot) load (material model|multimodel|modifier-model)'
  - '\[placebo\]: Exception loading patreon data!'
  - '\[AstralSorcery Patreon Effect Loader/WARN\] \[Astral Sorcery\]: Skipped .* patreon effects during loading due to malformed data!'

  # Mixins for absent mods. Happen when mod doesn't care to check if mod present first
  - '\[Client thread/WARN\] \[mixin\]: Error loading class: '

  # PetroPetunia cant be tweaked with decay https://github.com/quat1024/BotaniaTweaks/issues/63
  - 'Mod floralchemy is loaded. but flower petropetunia is not present??'

  # Probably safe, reported https://github.com/iLexiconn/LLibrary/issues/156
  - '\[LLibrary Core\]: Failed to fetch hierarchy node for .*. This may cause patch issues'

  # Known warning. reported
  - '\[TickCentral\]: Unable to get superclass as resource: '

  # plethora incompatible with betteranimals
  - '\[plethora\]: Cannot inject neural renderer for dev.itsmeow.betteranimals'

  # Immersive automatic recycling cant recycle some recipes
  - '\[immersiveengineering\]: Recipe has invalid inputs and will be ignored'

  # Actually Additions warning, no harm
  - '/WARN. \[FML\]: \*{5,}'
  - '/WARN. \[FML\]: \* Registry Item: The object .+ has been registered twice for the same name'
  - '/WARN. \[FML\]: \*  at \w+\.'

  # Additional properties for mixins
  - 'ERROR. \[mixin\]: Mixin config .+ does not specify "minVersion" property'

  # IC2 blocks and fluids that skipped
  - '\[ic2.(Item|Block)\]: The .* is not initialized.'

  # REAuth complaining about JAVA version
  - 'WARN. \[ReAuth\]: \+-----------------'
  - 'WARN. \[ReAuth\]: \| Please complain '
  - 'WARN. \[ReAuth\]: \| Java 8'
  - 'WARN. \[ReAuth\]: \| Updating would a'
  - 'WARN. \[ReAuth\]: \+-----------------'
  - 'WARN. \[ReAuth\]: Cryptography is restricted'
  - 'WARN. \[ReAuth\]: Certificates required'

  # Some case-sensetive warnings, can be ignored
  - 'WARN. \[.+AbstractResourcePack\]: ResourcePack: ignored non-lowercase namespace: META-INF in'

  # Some JEI errors, no harm
  - 'ERROR. \[jei|HadEnoughItems\]: A Recipe Handler has already been registered for '
  - 'ERROR. \[jei|HadEnoughItems\]: An interpreter is already registered for this item'
  - 'ERROR. \[jei|HadEnoughItems\]: Failed to register mod plugin'
  - 'ERROR. \[jei|HadEnoughItems\]: Recipe has no output. Extra Utilities 2 extrautils2:shortcut_hopper'

  # Happens when IC2 machine recipes changed
  - 'WARN. \[ic2\.Recipe\]: Late recipe loading failed\.'

  # Forestry using old BoP item entry
  - 'WARN. \[forestry\]: Missing block: sandstone'

  # Extra Utilities 2 fluids have no block representations
  - 'WARN. \[tconstruct-API\]: Itemstack 1xitem\.null.+ cannot represent material .+ since it is not associated with the material!'

  # Sledgehammer mod normal behaviour
  - '\[Sledgehammer\]: Skipping reloadSearchTrees'

  # Nutrition cant attach capabilities to Computercraft and Plethora. Doesnt matter since turtles cant eat anyway
  - 'Exception caught during firing event \S+AttachCapabilitiesEvent[\s\S\n]+nutrition.events.EventPlayerJoinWorld[\s\S\n]+'

  # JED complaining about file fingerprint
  - WARN. .Sledgehammer.. Certificate Fingerprint Violation Detected!
  - WARN. .justenoughdimensions.. \*{15}
  - 'WARN. .justenoughdimensions.. \*{5}   '

  # Safe WARNings, just for information
  - '\[LLibrary Core\]: Unable to call Core API! It has not been initialized yet!'
  - '\[brandonscore\]: No features were detected for mod: brandonscore.'
  - '\[EnderCore ASM\]: Ersatz patch applied. things may break!'
  - '\[enderio\]: Farming Station: Forestry integration for farming loaded but could not find Forestry sapling.'
  - '\[enderio\]: Farming Station: Forestry integration for fertilizing loaded but could not find Forestry fertilizer.'
  - 'WARN. \[FML\]: A mod has attempted to assign Block Block\{minecraft:air\} to the Fluid'
  - 'WARN. \[FML\]: No types have been added to Biome'
  - 'WARN. \[particleculling\]: Could not find particle class .+ If the mod is not installed, this can be ignored'
  - 'WARN. \[enderio\]: Not adding supplied recipe as a recipe already exists for the input: '
  - 'WARN. \[enderio\]: Item used in (Smeltery|cast) recipe .+ doesn.t smelt into a fluid'
  - 'WARN. \[(FML|FTB Library)\]: Replacing .+ with .+'
  - 'WARN. \[inventorytweaks\]: Failed to check item tree version: null'
  - 'WARN. \[keywizard\]: Conflicting mod detected, controls gui override may not work'
  - 'WARN. \[keywizard\]: Controls gui override enabled, this may cause problems with other mods'
  - 'WARN. \[mixin\]: Static binding violation: PRIVATE @Overwrite method func_76615_h in mixins\.phosphor\.json:common\.MixinChunk .+ cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded\.'
  - 'Unable to read property: material with value: iron for blockstate: .+ic2:te'
  - 'WARN. \[smoothfont\]: Fonts folder "fontfiles" does not exist'
  - 'WARN. \[smoothfont\]: renderChar method might be replaced\. Fix the space width to 4 \(MC default\)\.'
  - '\[solcarrot\]: Invalid Fingerprint!'
  - 'WARN. \[thermalexpansion\]: Thermal Expansion received an invalid IMC from chisel! Key was addcompactorpressrecipe'
  - 'WARN. \[toolprogression\]: Failed to set tool class of item'
  - 'WARN. \[mixin\]: Reference map .+ for mixins\.mixincompat\.json could not be read\. If this is a development environment you can ignore this message'
  - 'WARN. \[FML\]: Mod advancedrocketrycore has been disabled through configuration'
  - 'WARN. \[net\.minecraft\.client\.audio\.SoundManager\]: Missing sound for event: thaumcraft:runicshieldcharge'
  - 'WARN. \[ocsensors\]: Could not find field .+ in class '
  - 'ERROR. \[base\]: java\.io\.FileNotFoundException: biomesoplenty:textures/items/gem\.png'
  - 'WARN. \[FML\]: Unable to find recipe for minecraft:rabbit_stew'
  - 'WARN. \[FML\]: Unable to find recipe for minecraft:baked_potato'
  - 'WARN. \[(HadEnoughItems|jei)\]: Recipe registry plugin is slow, took \d{1,3}(\.\d+)? ms\.'

  ###################
  # Reported issues #
  ###################
  - '\[net.minecraft.entity.passive.EntityVillager\]: PriceRange.* smaller than'

  # Mechanics error https://github.com/wolforcept/mechanics/issues/13
  - '\[Mechanics\]: Failed to copy .+ property from block '
