#!/usr/bin/env node
/**
 * Precompile `src/zenscript.peggy` → `src/parser-generated.mjs`.
 *
 * The generated module is committed-and-regenerated (via the `prebuild` /
 * `pretest` hooks) so that no `readFileSync` of the grammar is needed at
 * runtime. This keeps the package immune to bundler changes and removes a
 * fragile FS dependency from `peggy.ts`.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

import peggy from 'peggy'

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC  = join(HERE, '..', 'src', 'zenscript.peggy')
const OUT  = join(HERE, '..', 'src', 'parser-generated.mjs')

const grammar = readFileSync(SRC, 'utf8')

const code = peggy.generate(grammar, {
  cache : true,
  format: 'es',
  output: 'source',
})

const banner = '// AUTO-GENERATED by scripts/build-parser.mjs from zenscript.peggy.\n'
  + '// Do NOT edit by hand; re-run `pnpm run build:parser`.\n'
  + '/* eslint-disable no-unused-vars, no-undef, prefer-const, no-var,'
  + ' no-cond-assign, no-empty, no-control-regex, no-misleading-character-class,'
  + ' no-useless-escape, no-redeclare, no-prototype-builtins,'
  + ' eslint-comments/no-unlimited-disable */\n'
  + '// @ts-nocheck\n'

writeFileSync(OUT, banner + code, 'utf8')
process.stdout.write(`Wrote ${OUT}\n`)
