# Mandatory dependencies
# Could exact mod name or regexp test (of the file or mod name)
# Could be single string, array of strings or a tree
dependencies:
  Thaumic Computers:
    - Thaumcraft-
    - OpenComputers-: Scala
  AE2 Wireless Fluid Terminal: 
    - "p455w0rd's Library"
    - AE2 Wireless Terminal Library
  Wireless Pattern Terminal: 
    - "p455w0rd's Library"
    - AE2 Wireless Terminal Library
  ContentTweaker Registry Orderer:
    ContentTweaker-: base-
  FindMeAnyDurability: Had Enough Items
  ModTweaker: MTLib
  JEIExporter-: Had Enough Items
  thaumicenergistics-: Thaumcraft-
  Tinkers' Evolution:
    - LibNine
    - Tinkers' Antique
  Loot Capacitor Tooltips: ^Ender IO$
  Compact Solars: Industrial Craft
  Deep Blood Evolution: 
    - Deep Mob Evolution
    - Blood Magic
  Ender Storage continuation: 'CodeChicken Lib 1.8.+'
  valkyrielib: RoughlyEnoughIDs
  Mekanism.+Generators: ^Mekanism Community Edition$
  RandomTweaker: Zen Utils
  RecurrentComplex: IvToolkit
  Trinity: 'NuclearCraft(: Overhauled)?$'
  CofH Core: Redstone Flux
  Actually Baubles: Actually Additions
  ^Quark$: AutoRegLib
  '^Quark: RotN': AutoRegLib
  DeepMobEvolution: ^Patchouli( ROFL Edition)?$
  ScalingHealth: SilentLib

# Optional dependents
dependents:
  Fugue:
    - ^Quark$
    - '^Quark: RotN'
    - ScalingHealth
    - Advanced Rocketry
    - "Armourer's Workshop"
    - Astral Sorcery
    - Botania Tweaks
    - Charset
    - CodeChickenLib
    - Custom Main Menu
    - Custom NPCs
    - Enchantments Control
    - EnderCore
    - Entity Distance
    - Extra Utilities 2
    - FoamFix
    - Forge Multipart
    - GregTech CE Unofficial
    - Hammer Lib
    - Howling Moon
    - IC2C Extra
    - In Control!
    - Lag Goggles
    - Logistics Pipes
    - LoliASM
    - MAGE
    - Mcjty Core
    - Nothirium
    - OpenDisks
    - OpenModsLib
    - OpenSecurity
    - 'Project:Red'
    - ReplayMod
    - Shoulder Surfing Reloaded
    - Simply Hot Spring
    - Smooth Font
    - Snow! Real Magic
    - Solar Flux Reborn
    - SplashAnimation
    - Subauqatic
    - Survival Inc.
    - TFC Medicinal
    - Thaumic Speedup
    - Valkyrie
    - Vampirism
    - Water Power
    - Xaero Plus
    - ^XNet
    - ZeroCore
    - Tinkers' Evolution

# This section maps a base mod's CurseForge project ID to an array of project IDs for its forks or variants.
# It helps the tool recognize that different versions of a mod (e.g., Tinker's Construct and its forks)
# should be treated as the same core mod when resolving dependencies.
# To add a new entry, use the base mod's project ID as the key and list the fork project IDs in the array.
# Example:
#   <base_mod_id>: [<fork_1_id>, <fork_2_id>]
forks:
  74072: [1242239] # Tinker's Construct
  223794: [570458] # Applied
  228404: [1252600] # Actually Additions
  236542: [1024225] # Advanced Rocketry
  238222: [557549] # HEI
  243121: [417392] # Quark
  245211: [977883] # TOP
  248453: [456403] # Forgelin
  268387: [398267] # Extended Crafting
  268560: [813408] # Mekanism
  357178: [419286] # MixinBootstrap
  434516: [261348] # Avaritia
